// ==UserScript==
// @name         AI Music Banner for YouTube
// @namespace    https://github.com/VincentLorenzi/AI-Music-Banner-for-YouTube
// @version      1.0
// @description  Shows a prominent banner above YouTube videos when the description mentions AI-generated music.
// @author       Vincent Lorenzi
// @license      GNU GPL 3.0
// @match        https://www.youtube.com/*
// @homepageURL  https://github.com/VincentLorenzi/AI-Music-Banner-for-YouTube
// @updateURL    https://raw.githubusercontent.com/VincentLorenzi/AI-Music-Banner-for-YouTube/ai-music-banner.user.js
// @downloadURL  https://raw.githubusercontent.com/VincentLorenzi/AI-Music-Banner-for-YouTube/ai-music-banner.user.js
// ==/UserScript==


(function () {
    'use strict';

    console.log('AI Banner: userscript executing');

    const DEFAULT_KEYWORDS = [
        // generic phrases
        "ai generated",
        "ai-generated",
        "generated by ai",
        "created by ai",
        "made with ai",
        "produced by ai",
        "synthesized by ai",
        "machine generated",
        "algorithmic composition",
        "algorithmically generated",
        "ai vocals",
        "ai voice",
        "vocals generated",
        "vocal synth",
        "synthetic vocals",
        "vocal synthesis",
        "ai technology",
        "ai generation",
        "ai generation tools",
        "assistance of ai",
        "assisted by ai",
        "created with the assistance of ai",

        // common AI music services and tools (variants)
        "mubert",
        "boomy",
        "aiva",
        "amper",
        "endel",
        "soundful",
        "soundraw",
        "jukebox",
        "openai jukebox",
        "amper music",
        "jukify",
        "boomplay ai",
        "landr",
        "sonicai",
        "audiobridge",
        "soundhut",

        // research / libraries
        "nsynth",
        "magenta",
        "melnet",
        "demucs",
        "spleeter",

        // marketing / product phrases
        "ai-assisted",
        "ai assisted",
        "ai produced",
        "ai composition",
        "vocals by ai",
        "instrumental generated by ai",
        "composed with ai",
        "music generated with",

        // short forms / acronyms
        "a.i. generated",
        "a.i. vocals",
        "ai-generated music"
    ];

    // Add explicit product/service keywords and common phrasings
    DEFAULT_KEYWORDS.push(
        "chatgpt",
        "suno",
        "gemini",
        "sora",
        "artificial intelligence",
        "ai tools",
        "created with the help of",
        "created with the help of artificial"
    );

    const STORAGE_KEYS = {
        USER_KEYWORDS: 'ai_banner_user_keywords',
        ENABLED: 'ai_banner_enabled'
    };

    const DEFAULT_CONFIG = {
        bannerText: 'AI generated music',
        bannerColor: '#cc0000',
        textColor: '#ffffff',
        detectionEnabled: true
    };

    let config = Object.assign({}, DEFAULT_CONFIG);

    // Lightweight runtime flags
    let regexCache = null;
    let detectTimer = null;
    const DETECT_DEBOUNCE_MS = 250;

    function scheduleDetect() {
        if (detectTimer) clearTimeout(detectTimer);
        detectTimer = setTimeout(() => { detectAndNotify(); detectTimer = null; }, DETECT_DEBOUNCE_MS);
    }

    // If user keywords are stored later, clear cache (not frequently used)
    function clearRegexCache() { regexCache = null; }

    function getUserKeywords() {
        try {
            const stored = GM_getValue(STORAGE_KEYS.USER_KEYWORDS);
            if (Array.isArray(stored) && stored.length) return stored;
        } catch (e) { }
        return DEFAULT_KEYWORDS;
    }

    function isEnabled() {
        try {
            const v = GM_getValue(STORAGE_KEYS.ENABLED);
            if (typeof v === 'boolean') return v;
        } catch (e) { }
        return true;
    }

    // per-channel dismissal removed — simpler behavior

    function createBanner(text, channelId) {
        removeBanner();

        const banner = document.createElement('div');
        banner.id = 'ai-music-banner';
        banner.setAttribute('role', 'alert');
        banner.style.background = config.bannerColor;
        banner.style.color = config.textColor;
        banner.style.padding = '12px 16px';
        banner.style.fontSize = '20px';
        banner.style.fontWeight = '700';
        banner.style.textAlign = 'center';
        banner.style.zIndex = '99999';
        banner.style.display = 'flex';
        banner.style.alignItems = 'center';
        banner.style.justifyContent = 'center';
        banner.style.gap = '12px';
        // keep banner visible by fixing to top-center
        banner.style.position = 'fixed';
        banner.style.top = '8px';
        banner.style.left = '50%';
        banner.style.transform = 'translateX(-50%)';
        banner.style.boxShadow = '0 2px 12px rgba(0,0,0,0.5)';
        banner.style.borderRadius = '6px';

        const span = document.createElement('span');
        span.textContent = text;

        const controls = document.createElement('div');
        controls.style.display = 'flex';
        controls.style.alignItems = 'center';
        controls.style.gap = '8px';

        // non-dismissible banner (no close button)
        banner.appendChild(span);

        // Append banner to document.body so it is not removed when YouTube replaces player DOM
        try {
            // compute a top offset below the masthead if present
            const masthead = document.querySelector('#masthead-container') || document.querySelector('ytd-masthead') || document.querySelector('#container.ytd-masthead');
            const headerHeight = masthead ? (masthead.getBoundingClientRect().height || 0) : 0;
            const topOffset = Math.max(8, Math.ceil(headerHeight) + 8);
            banner.style.top = topOffset + 'px';
        } catch (e) {
            // leave existing top value
        }
        // keep pointer events enabled so users cannot accidentally click through
        banner.style.pointerEvents = 'auto';
        // set an explicit display style to make restoration easier
        banner.style.display = 'flex';
        document.body.appendChild(banner);
        // protect banner from being hidden or clicked-through
        try { protectBanner(); } catch (e) { }

        return banner;
    }

    function removeBanner() {
        const old = document.getElementById('ai-music-banner');
        if (old && old.parentElement) old.parentElement.removeChild(old);
    }

    function normalizeText(s) {
        if (!s) return '';
        let t = s.replace(/<[^>]+>/g, ' ');
        t = t.replace(/[\p{P}\p{S}]+/gu, ' ');
        t = t.toLowerCase();
        t = t.replace(/\s+/g, ' ').trim();
        return t;
    }

    function buildRegexesFromKeywords(keywords) {
        if (regexCache) return regexCache;
        try {
            regexCache = keywords.map(k => {
                const esc = k.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
                const pattern = esc.replace(/\s+/g, '[\\s\\-\\._]*');
                return new RegExp('\\b' + pattern + '\\b', 'i');
            });
        } catch (e) { regexCache = []; }
        return regexCache;
    }

    function extractDescriptionText() {
        // Try known YouTube description nodes (collect multiple nodes when present)
        const selectors = [
            '#description',
            'ytd-expander#description',
            'yt-formatted-string.content',
            'ytd-watch-metadata #description',
            'yt-core-attributed-string.yt-core-attributed-string--white-space-pre-wrap',
            'yt-core-attributed-string',
            'yt-attributed-string#attributed-description-text',
            'yt-attributed-string#attributed-snippet-text',
            'ytd-text-inline-expander',
            '#description-text-container',
            '#description-inner'
        ];

        const collected = [];
        for (const sel of selectors) {
            const nodes = document.querySelectorAll(sel);
            if (nodes && nodes.length) {
                nodes.forEach(n => {
                    const txt = n.innerText || n.textContent || '';
                    if (txt && txt.trim()) collected.push(txt.trim());
                });
            }
        }

        if (collected.length) return collected.join('\n\n');

        // fallback: try to read any formatted-string inside ytd-watch
        const alt = document.querySelector('ytd-watch-flexy');
        if (alt) {
            const fs = alt.querySelector('yt-formatted-string');
            if (fs) return fs.innerText || fs.textContent || '';
        }
        // Additional fallbacks: JSON-LD structured data, ytInitialPlayerResponse, meta description
        try {
            const ld = document.querySelector('script[type="application/ld+json"]');
            if (ld && ld.textContent) {
                try {
                    const j = JSON.parse(ld.textContent);
                    if (j && j.description) {
                        console.debug('[AI Banner] description from JSON-LD');
                        updateDebugOverlay('desc source: JSON-LD');
                        return j.description;
                    }
                } catch (e) { /* ignore JSON parse errors */ }
            }
        } catch (e) { }

        try {
            let ipr = window.ytInitialPlayerResponse;
            if (!ipr) {
                // Fallback: search inline scripts for ytInitialPlayerResponse assignment
                const scripts = Array.from(document.scripts || []);
                for (const s of scripts) {
                    const t = s.textContent || '';
                    const m = t.match(/ytInitialPlayerResponse\s*=\s*(\{.*\})\s*;/s);
                    if (m && m[1]) {
                        try { ipr = JSON.parse(m[1]); break; } catch (e) { /* ignore parse errors */ }
                    }
                }
            }
            if (ipr && ipr.videoDetails && ipr.videoDetails.shortDescription) {
                console.debug('[AI Banner] description from ytInitialPlayerResponse.videoDetails.shortDescription');
                updateDebugOverlay('desc source: ytInitialPlayerResponse');
                return ipr.videoDetails.shortDescription;
            }
        } catch (e) { }

        try {
            const meta = document.querySelector('meta[name="description"]');
            if (meta && meta.content) {
                console.debug('[AI Banner] description from meta[name="description"]');
                updateDebugOverlay('desc source: meta');
                return meta.content;
            }
        } catch (e) { }

        return '';
    }

    // Helper to show banner only once per detection
    function bannerExists() { return !!document.getElementById('ai-music-banner'); }


    function extractChannelId() {
        // Attempt to read channel id from meta or link
        try {
            const link = document.querySelector('ytd-channel-name a');
            if (link && link.href) return link.href.split('/').pop();
        } catch (e) { }
        try {
            const meta = document.querySelector('meta[itemprop="channelId"]');
            if (meta) return meta.getAttribute('content');
        } catch (e) { }
        return null;
    }

    function shouldSkipForChannel(channelId) {
        // Per-channel dismissals removed — never skip by channel
        return false;
    }

    let lastVideoId = null;
    // track number of expansion attempts per video
    const attemptedExpansions = new Map();

    function getVideoId() {
        const url = new URL(location.href);
        return url.searchParams.get('v') || null;
    }

    async function detectAndNotify(attempt = 1) {
        if (!isEnabled()) { removeBanner(); return; }

        const videoId = getVideoId();
        // If there's no video on this page, remove any banner and stop
        if (!videoId) { removeBanner(); return; }

        lastVideoId = videoId;

        const delay = 500 * attempt; // increased backoff to allow description load
        setTimeout(async () => {
            try {
                // wait for description (or structured fallback) to be populated before extracting
                try {
                    await waitForDescriptionLoad(8000, 300, videoId);
                } catch (e) { /* ignore */ }
                const desc = extractDescriptionText();
                const chanId = extractChannelId();
                // minimal logging for errors only

                // If no video id on page, optionally show banner if description contains keywords
                if (!videoId) {
                    const normNoVid = normalizeText(desc || '');
                    const keywordsNoVid = getUserKeywords();
                    const regexesNoVid = buildRegexesFromKeywords(keywordsNoVid);
                    let matchesNoVid = 0;
                    for (const r of regexesNoVid) if (r.test(normNoVid)) matchesNoVid++;
                    if (matchesNoVid > 0 && !bannerExists()) {
                        console.info('[AI Banner] show on non-video page matched', matchesNoVid);
                        updateDebugOverlay('matched (no video): ' + matchesNoVid);
                        createBanner(config.bannerText, chanId);
                    }
                    return;
                }

                if (shouldSkipForChannel(chanId)) { removeBanner(); return; }

                const norm = normalizeText(desc);
                const keywords = getUserKeywords();
                const regexes = buildRegexesFromKeywords(keywords);

                let matches = 0;
                for (const r of regexes) {
                    if (r.test(norm)) matches++;
                }

                if (matches > 0) {
                    console.info('[AI Banner] match count', matches, 'showing banner');
                    if (!bannerExists()) createBanner(config.bannerText, chanId);
                } else {
                    // retry a few times if we didn't find anything but description seems empty
                    if ((!desc || !desc.trim()) && attempt < 4) {
                        // retry when description empty
                        detectAndNotify(attempt + 1);
                        return;
                    }
                        // no matches; ensure banner removed
                    removeBanner();
                }
            } catch (e) {
                console.warn('[AI Banner] detection error', e);
                if (attempt < 4) detectAndNotify(attempt + 1);
            }
        }, delay);
    }

    // Wait until candidate description content or structured fallbacks appear
    function waitForDescriptionLoad(timeout = 5000, interval = 250, videoId = null) {
        return new Promise((resolve) => {
            const start = Date.now();
            const check = () => {
                try {
                    // if JSON-LD has description
                    const ld = document.querySelector('script[type="application/ld+json"]');
                    if (ld && ld.textContent && /"description"\s*:\s*"/.test(ld.textContent)) { resolve(true); return; }
                    // meta description
                    const meta = document.querySelector('meta[name="description"]');
                    if (meta && meta.content && meta.content.trim().length > 20) { resolve(true); return; }
                    // any description node with reasonable length
                    const nodes = findDescriptionNodes();
                    for (const n of nodes) {
                        const txt = (n.innerText || n.textContent || '').trim();
                        if (txt && txt.length > 40) { resolve(true); return; }
                        // detect common collapsed snippet indicators and try to expand
                        try {
                            if (txt && (/\.\.\.|…|\.{1,3}/.test(txt) || /afficher|show more/i.test(txt))) {
                                try { if (videoId) expandDescriptionIfCollapsed(videoId); else expandDescriptionIfCollapsed(getVideoId()); } catch (e) { }
                            }
                        } catch (e) { }
                    }
                } catch (e) { }
                if (Date.now() - start > timeout) { resolve(false); return; }
                setTimeout(check, interval);
            };
            check();
        });
    }

    // SPA navigation handling
    function setupNavigationHandling() {
        // YouTube dispatches a custom event on navigation finish; try to listen
        window.addEventListener('yt-navigate-finish', () => { scheduleDetect(); });

        // MutationObserver fallback on page manager
        const pageManager = document.getElementById('page-manager') || document.querySelector('ytd-app');
        if (!pageManager) return;

        let timer = null;
        const mo = new MutationObserver((mutations) => {
            if (timer) clearTimeout(timer);
            timer = setTimeout(() => {
                scheduleDetect();
                // rewire description observer on navigation changes
                ensureDescriptionObserver();
            }, 350);
        });
        mo.observe(pageManager, { childList: true, subtree: true });
    }

    // Observe description nodes specifically to trigger detection as soon as text appears/changes
    let descObserver = null;
    function findDescriptionNodes() {
        const selectors = [
            '#description',
            'ytd-expander#description',
            'yt-formatted-string.content',
            'ytd-watch-metadata #description',
            'yt-core-attributed-string.yt-core-attributed-string--white-space-pre-wrap',
            'yt-core-attributed-string',
            'yt-attributed-string#attributed-description-text',
            'yt-attributed-string#attributed-snippet-text',
            'ytd-text-inline-expander',
            '#description-text-container',
            '#description-inner'
        ];
        const nodes = new Set();
        for (const s of selectors) {
            try {
                document.querySelectorAll(s).forEach(n => nodes.add(n));
            } catch (e) { }
        }
        // also include any formatted-string under ytd-watch-flexy
        try {
            const alt = document.querySelector('ytd-watch-flexy');
            if (alt) alt.querySelectorAll('yt-formatted-string').forEach(n => nodes.add(n));
        } catch (e) { }
        return Array.from(nodes);
    }

    // Try to click the 'show more' expander for collapsed descriptions once per video
    function expandDescriptionIfCollapsed(videoId) {
        try {
            const incTry = () => {
                const cur = attemptedExpansions.get(videoId) || 0;
                attemptedExpansions.set(videoId, cur + 1);
            };

            // typical YouTube expander buttons / known selectors
            const expSelectors = [
                'tp-yt-paper-button#expand',
                'tp-yt-paper-button#expand-sizer',
                'tp-yt-paper-button#more',
                'tp-yt-paper-button[aria-label*="Show more"]',
                'tp-yt-paper-button[aria-label*="Afficher"]',
                'yt-formatted-string.more-button',
                'ytd-expander tp-yt-paper-button#more',
                'ytd-expander#description tp-yt-paper-button',
                'ytd-expander#description a#more',
                'ytd-expander#description a'
            ];

            for (const s of expSelectors) {
                try {
                    const el = document.querySelector(s);
                    if (el && el.offsetParent !== null) {
                        // brief highlight to make clicked element visible for debugging
                        try { el.style.outline = '3px solid rgba(255,200,0,0.95)'; } catch (e) { }
                        setTimeout(() => { try { el.style.outline = ''; } catch (e) { } }, 1200);
                        try { el.click(); } catch (e) { el.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })); }
                        incTry();
                        return true;
                    }
                } catch (e) { }
            }

            // If the `#description` node itself is clickable (some layouts), click it
            try {
                const descNode = document.getElementById('description') || document.querySelector('ytd-expander#description');
                if (descNode && descNode.offsetParent !== null) {
                    const role = descNode.getAttribute && descNode.getAttribute('role');
                    const hasHandler = descNode.onclick || descNode.hasAttribute && (descNode.hasAttribute('tabindex') || descNode.getAttribute('aria-expanded') !== null);
                    if (role === 'button' || hasHandler) {
                        try { descNode.click(); } catch (e) { descNode.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })); }
                        incTry();
                        return true;
                        return true;
                    }
                }
            } catch (e) { }

            // Try to find a button-like element inside the ytd-expander with localized text
            const container = document.querySelector('ytd-expander#description') || document.querySelector('ytd-watch-flexy');
            if (container) {
                const candidates = Array.from(container.querySelectorAll('*'));
                for (const c of candidates) {
                    try {
                        const txt = (c.getAttribute && (c.getAttribute('aria-label') || c.getAttribute('title'))) || (c.textContent || '');
                        if (!txt) continue;
                        const low = txt.toLowerCase();
                        if (/(show(\s+)?more|afficher(\s+)?plus|afficher(\s+)?la(\s+)?suite|voir(\s+)?plus|suite)/i.test(low)) {
                            if (c.offsetParent === null) continue;
                            try { c.click(); } catch (e) { c.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })); }
                            incTry();
                            return true;
                        }
                    } catch (e) { }
                }
            }

            // Last resort: look for any link that contains ellipsis text indicating collapsed content
            const links = Array.from(document.querySelectorAll('a, button, tp-yt-paper-button'));
            for (const l of links) {
                try {
                    const text = (l.textContent || l.getAttribute('aria-label') || '').toLowerCase();
                    if (text.includes('...') || text.includes('afficher') || text.includes('show more') || text.includes('afficher plus')) {
                        if (l.offsetParent === null) continue;
                        try { l.click(); } catch (e) { l.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })); }
                        incTry();
                        return true;
                    }
                } catch (e) { }
            }

        } catch (e) { console.warn('[AI Banner] expandDescriptionIfCollapsed error', e); }
        return false;
    }

    function ensureDescriptionObserver() {
        try {
            // disconnect old
            if (descObserver) { descObserver.disconnect(); descObserver = null; }
            const nodes = findDescriptionNodes();
            if (!nodes || !nodes.length) return;
            descObserver = new MutationObserver((mutations) => {
                for (const m of mutations) {
                    if (m.type === 'characterData' || m.type === 'childList' || m.type === 'subtree') {
                        // trigger a quick detection (debounced)
                        scheduleDetect();
                        return;
                    }
                }
            });
            for (const n of nodes) {
                try {
                    descObserver.observe(n, { characterData: true, childList: true, subtree: true });
                } catch (e) { }
            }
        } catch (e) { console.warn('[AI Banner] ensureDescriptionObserver error', e); }
    }

    // Production: no user menu commands (debug commands removed)

    // Harden banner: prevent clicks from hiding it and restore if style.display changed
    function protectBanner() {
        try {
            const banner = document.getElementById('ai-music-banner');
            if (!banner) return;
            // stop clicks from being interpreted by other handlers
            banner.addEventListener('click', (ev) => { ev.stopPropagation(); }, true);
            // observe style changes and restore visibility if hidden
            const bmo = new MutationObserver((mutations) => {
                for (const m of mutations) {
                    if (m.type === 'attributes' && m.attributeName === 'style') {
                        const el = m.target;
                        const disp = window.getComputedStyle(el).display;
                        if (disp === 'none') {
                            try { el.style.display = 'flex'; } catch (e) { }
                        }
                    }
                }
            });
            bmo.observe(banner, { attributes: true, attributeFilter: ['style'] });
        } catch (e) { console.warn('[AI Banner] protectBanner error', e); }
    }

    function init() {
        try {
            detectAndNotify();
            setupNavigationHandling();
        } catch (e) {
            console.warn('AI Banner init error', e);
        }
    }

    // Run now and also when the page fully loads (fallback)
    init();
    window.addEventListener('load', () => { setTimeout(init, 200); });

})();
